### ISSUE TITLE
Can't build binary release pls

### ISSUE THREAD

**Issue by ghost** [BusyJay/gpg-bridge#1]
Sadly I can't install this toll since I would need to habe a version of VS installed since it seems to need the link.exe

**Comment by BusyJay** [comment]
rustup.rs is a good tool to setup the environment. It's recommended to build it by yourself, as it's the safest way to build a binary using trusted tool from (trusted) open source code.

However, if you wish to get a prebuilt binary any way, you can try [gpg-bridge.zip](https://github.com/BusyJay/gpg-bridge/files/5032613/gpg-bridge.zip). I build it on Windows 10, not sure whether it works with other versions of Windows.

SHA256: D8EC3A158E7804EB0B2727176A225C07327EDDD664BDB3AABB9162875D14960F

**Comment by ghost** [comment]
I was also trying to build it and made a guide [here](https://github.com/rust-lang/rustup/issues/1455#issuecomment-685113014) for people like me, who have never compiled anything on windows and don't generally use windows extensively. It's just 6 commands in the shell, and a bit of patience.
