### ISSUE TITLE
make a release

### ISSUE THREAD

**Issue by Andrysky** [BusyJay/gpg-bridge#7]
hi it would be great to have a release so you can download and use it) without installing rust

**Comment by BusyJay** [comment]
You can download it from github action. Here is a details guide: https://docs.github.com/en/actions/managing-workflow-runs/downloading-workflow-artifacts. The binary is built automatically on every commit of master branch.

**Comment by colemickens** [comment]
It might also be worth issuing a release. Those artifacts are only accessible to signed-in GitHub users, and only for 90 days.

**Comment by BusyJay** [comment]
Good point! I will check whether I can make the process automatically with Github actions.

**Comment by FWest98** [comment]
I can no longer download the artifacts unfortunately. Would you be able to make a release?

**Comment by BusyJay** [comment]
I just published a release manually by triggering a rebuild on latest code. https://github.com/BusyJay/gpg-bridge/releases/tag/v0.1.0.
